<?php
//print out form data



function howcool_menu() {

  $items = array();

  $items['form'] = array(
  'title' => 'HowCool!Form',
  'description' => 'Page Decription',
  'page callback' => 'form_view',
  //'page callback' => 'drupal_get_form',
  //'page arguments' => array(1),     
  'access arguments' => array('access content'),
  'type' => MENU_NORMAL_ITEM,
  'file' => 'howcool.inc',
  );

  $items['result/%'] = array(
    'title'=> 'HowCool!Result',
    'description'=>'Show result',
    'page callback'=>'result_view',
    'page arguments' => array(1),
    'access arguments'=>array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'howcool.inc',
   
  );
  
  $items['detail/%'] = array(
    'title'=> 'HowCool!Result',
    'description'=>'Show result',
    'page callback'=>'detail_view',
    'page arguments' => array(1),
    'access arguments'=>array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'howcool.inc',
   
  );
  
  $items['management'] =array(
    'title'=> 'HowCool!DataManagement',
    'description'=>'Show Data',
    'page callback'=>'data_view',
    'access arguments'=>array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'datamanagement.inc',
   
  );
  
  return $items;
}


/**
    How Cool Display?

*/

function form_decision($data){

  return $data['page']['#value'];
}


function form_view(){

   drupal_add_css(drupal_get_path('module', 'howcool') . '/css/jquery.ratings.css');
   drupal_add_css(drupal_get_path('module', 'howcool') . '/css/reset.css');
   drupal_add_css(drupal_get_path('module', 'howcool') . '/css/text.css');
   drupal_add_css(drupal_get_path('module', 'howcool') . '/css/960.css');
   drupal_add_js(drupal_get_path('theme', 'foundation') .'/cufon-yui.js', 'theme');
   drupal_add_js(drupal_get_path('theme', 'foundation') .'/supermarket_400.font.js', 'theme');
   //drupal_add_css(drupal_get_path('module', 'howcool') . '/css/uncompressed/demo.css');
  //$show = 'this is form--->';

  $show .= drupal_get_form('form_generation',$form_state);
  return $show;
}

function result_view($input){
  //$show = 'this is result!!'.$input;
  //$show .= print_r(get_result($input),1);
  drupal_add_js(drupal_get_path('theme', 'foundation') .'/cufon-yui.js', 'theme');
  drupal_add_js(drupal_get_path('theme', 'foundation') .'/supermarket_400.font.js', 'theme');
  $show =gen_graph(get_result($input));
  $_SESSION['hash'] =$input;
  $show .= drupal_get_form('form_detail',$form_state);
  return $show;
}

function detail_view($input){
   drupal_add_css(drupal_get_path('module', 'howcool') . '/css/reset.css');
   drupal_add_css(drupal_get_path('module', 'howcool') . '/css/text.css');
   drupal_add_css(drupal_get_path('module', 'howcool') . '/css/960.css');
   drupal_add_css(drupal_get_path('module', 'howcool') . '/css/check_lists.css');
   drupal_add_js(drupal_get_path('theme', 'foundation') .'/cufon-yui.js', 'theme');
   drupal_add_js(drupal_get_path('theme', 'foundation') .'/supermarket_400.font.js', 'theme');
   drupal_add_css(drupal_get_path('module', 'howcool') . '/css/jquery.ratings.css');
 $raw_data = DataManagement::getAllDetail();
 $info = array();
  
  $keep_info = unserialize(DataManagement::getDetailData($input));

  for($i = 0 ;$i<count($keep_info['data']);$i++){
  
    $scale = $keep_info['data'][$i]['value'];
    $key = $keep_info['data'][$i]['key'];

    $info[$i] = array('image_path' => $raw_data[$key]['image_path'] ,
                      'name' =>$raw_data[$key]['name'],
                      'carbon' =>($raw_data[$key]['carbon_factor']*$scale),
                      'water' =>($raw_data[$key]['water_factor']*$scale),
                      'scale' =>$scale,
                      );
    
  }
  
  $data = array(
    'carbon' => '0.99 กิโลกรรม',
    'water' => '5.75 ลิตร',
    'info'=>$info,
  );
  $r_output = new ResultOutput();
  $output = $r_output->showDetail($data);
  $output .= drupal_get_form('form_back_toResult',$form_state);
  return $output;
}

/**
    How Cool Form Stucture

*/
function form_back_toResult($form_state){
  $output = new DisplayOutput();
  $form['white_class'] =$output->openDiv('white_class');
  $form['block5']=$output->createGrid(5);
  $form['grid_open'] = $output->openGrid(2);
  $form['back'] = array(
    '#type' => 'submit',
    '#value' => t('Back'),
   
  );
  $form['grid_close'] = $output->closeGrid();
  $form['block6']=$output->createGridWithLine(5);
  $form['close_white_class'] =$output->closeDiv();
  //$form['submit_close_container'] = $output->closeContainer();
  return $form;

}

function form_back_toResult_submit($form_state){
   $hash =$_SESSION['hash'];
   drupal_goto('result/'.$hash);
}

function form_detail($form_state){
  $output = new DisplayOutput();
  $form['white_class'] =$output->openDiv('white_class');
  $form['block5']=$output->createGrid(5);
  $form['grid_open'] = $output->openGrid(2);
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Next'),
    
  );
  $form['grid_close'] = $output->closeGrid();
  $form['block6']=$output->createGridWithLine(5);
  $form['close_white_class'] =$output->closeDiv();
  //$form['submit_close_container'] = $output->closeContainer();
  return $form;
}
function form_detail_submit($form_state){
   $hash =$_SESSION['hash'];
   drupal_goto('detail/'.$hash);
}

function form_generation($form_state,$page){
  if(empty($form_state['values'])){
    //drupal_set_message(form_decision(เ($form_state)));  
    return email_form($form_state);
  }else if($form_state['values']['op']=='Back'){
    //drupal_set_message(form_decision(form_back_generation($form_state)));  
    return form_back_generation($form_state);
  }else{
    //drupal_set_message(form_decision(form_next_generation($form_state)));  
    return form_next_generation($form_state);
  
  }
}

function form_next_generation($form_state){
  
  switch($form_state['values']['page']){
    case 'email': return personal_form($form_state);
      break;
    case 'personal': return check_form($form_state);
      break;
     case 'check' : return scale_form($form_state);
      break;
  }
}

function form_back_generation($form_state){
    
  switch($form_state['values']['page'] ){
    case 'personal':   return email_form($form_state);
      break; 
    case 'check': return personal_form($form_state);
      break;
     case 'scale' : return check_form($form_state);
      break;
  } 
  
  
}

function form_generation_submit(&$form, &$form_state) {
  $form_state['storage']['values'] = $form_state['values'];
  $form_state['rebuild'] = TRUE;
  //Jumper!!!
  if($form_state['values']['page']=='scale' && $form_state['values']['op']!='Back'){
    logic($form_state);
  }
}

function email_form($form_state){
  //$form['email']= array('#type' => 'hidden', '#value' => $form_state['values']['email']);
  $form['sex']= array('#type' => 'hidden', '#value' => $form_state['values']['sex']);
  $form['age']= array('#type' => 'hidden', '#value' => $form_state['values']['age']);
  $form['job']= array('#type' => 'hidden', '#value' => $form_state['values']['job']);
  $form['address']= array('#type' => 'hidden', '#value' => $form_state['values']['address']);
  $form['hight']= array('#type' => 'hidden', '#value' => $form_state['values']['hight']);
  $form['weight']= array('#type' => 'hidden', '#value' => $form_state['values']['weight']);
  $form['status']= array('#type' => 'hidden', '#value' => $form_state['values']['status']);
  
  $output = new DisplayOutput();
  $form['openContainer'] = $output->openContainer(12);
  //$form['openGrid']= $output->createGrid(6);
  $form['headLine1']= $output->createGridWithLine(12,"        
                <div class='sufon HeadResultTitle HeadResultCenter'>กรุณากรอกอีเมล์ของท่าน</div> 
                <hr class='white-bottom'/>     
         ",'spacer');
  $form['block1']=$output->createGrid(1);
  $form['openGrid']= $output->openGrid(4);
  //insert picture
  $form['image'] = $output->insertPicture('images/picquiz.png');
  $form['closeGrid'] = $output->closeGrid();
  $form['block2']=$output->createGridWithLine(4);
  $form['block3']=$output->createGrid(7);
  $form['openEmailGrid'] = $output->openGrid(4);
  /*$form['myhtml'] = array(
    '#type'=>'markup',
    '#value'=>theme('headline','Yo Mannn'),
  
  );*/
  if(empty($form_state['values']['email'])){
    $form['email'] = array(
      '#type' => 'textfield', 
      '#title' => t('Email'), 
      '#size' => 30, 
      '#maxlength' => 128, 
      '#required' => TRUE,
    );
  }else{
    $form['email'] = array(
      '#type' => 'textfield', 
      '#title' => t('Email'), 
      '#size' => 30, 
      '#maxlength' => 128, 
      '#default_value' => $form_state['values']['email'],
      '#required' => TRUE,
    );
  }

  $form['page'] = array('#type' => 'hidden', '#value' => 'email');
  
  /*
  $form['myhtml_footer'] = array(
    '#type'=>'markup',
    '#value'=>theme('headline','Last Man'),
  
  );
  */
  $form['closeEmailGrid'] = $output->closeGrid();
  $form['block4']=$output->createGrid(4);
  $form['closeContainer'] = $output->closeContainer();
  
  //$form['submit_container'] = $output->openContainer(12);
  $form['white_class'] =$output->openDiv('white_class');
  $form['block5']=$output->createGrid(5);
  $form['grid_open'] = $output->openGrid(2);
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Next'),
    
  );
  $form['grid_close'] = $output->closeGrid();
  $form['block6']=$output->createGridWithLine(5);
  $form['close_white_class'] =$output->closeDiv();
  //$form['submit_close_container'] = $output->closeContainer();
  return $form;
}

function personal_form($form_state){
     drupal_add_js(drupal_get_path('theme', 'foundation') .'/cufon-yui.js', 'theme');
     drupal_add_js(drupal_get_path('theme', 'foundation') .'/supermarket_400.font.js', 'theme');

   //  drupal_add_css(drupal_get_path('module','howcool'). '/css/
  $output=new DisplayOutput();
 
  $form['conatiner12']=$output->openContainer();
  $form['headLine1']= $output->createGridWithLine(12,"      <div  class='sufon HeadResultTitle HeadResultCenter'>กรุณากรอกข้อมูลส่วนตัวของท่าน</div> 
                <hr class='white-bottom'/>     ",'spacer');
  $form['grid1_1']=$output->createGrid(1,'<p></p>');
  $form['grid4_111']=$output->createGrid(4,"<img src=' ". drupal_get_path('module', 'howcool') . '/images/p1_0.png' ."'> ");
  $form['grid1_12']=$output->createGrid(1,'<p></p>');
  $form['grid1_13']=$output->openGrid(6,'<p></p>');
  $form['openDiv']=$output->openDiv('pop');
    //$form['openDiv']=$output->openDiv('now');
  $form['email']= array('#type' => 'hidden', '#value' => $form_state['values']['email']);
  if(empty($form_state['values']['sex'])){
    $form['sex'] = array(
      '#type' => 'select', 
      '#title' => t('เพศ'),
     //'#default_value' => variable_get('comment_preview', 1), 
       '#options' => array("null"=>t('เพศ'),"male"=>t('ชาย'), "female"=>t('หญิง')),
      '#required' =>TRUE,
    );
  }else{
    $form['sex'] = array(
     '#type' => 'select', 
     '#title' => t('เพศ'), 
     '#default_value' => $form_state['values']['sex'],
     '#options' => array("null"=>t('เพศ'),"male"=>t('ชาย'), "female"=>t('หญิง')),
     '#options' => array("male"=>t('ชาย'), "female"=>t('หญิง')),
     '#required' =>TRUE,
    );
  }
 
  if(empty($form_state['values']['age'])){
    $form['age'] = array(
      '#type' => 'select', 
      '#title' => t('ช่วงอายุ'), 
      '#options' =>  drupal_map_assoc(array_merge(Config::$age_renges,range(1,130) ) ),
      '#required' =>TRUE,
    );
   
  }else{
    $form['age'] = array(
      '#type' => 'select', 
      '#title' => t('ช่วงอายุ'), 
      '#options' => drupal_map_assoc(array_merge(Config::$age_renges,range(1,130) ) ),
      '#required' =>TRUE,
      '#default_value' => $form_state['values']['age'],
    );
     

  }
  if(empty($form_state['values']['job'])){
    $form['job'] = array(
      '#type' => 'select', 
      '#title' => t('อาชีพ'), 
      //'#default_value' => variable_get('เลือกอาชีพ','student'),
      '#options' =>array_merge(Config::$job_renges, Config::getDbValue('occupation', 'name')),
 
    );
  }else{
    $form['job'] = array(
      '#type' => 'select', 
      '#title' => t('อาชีพ'), 
      '#default_value' =>  Config::$job_renges,
      '#options' =>array_merge(Config::$job_renges, Config::getDbValue('occupation', 'name')),
 
    );
  }
  if(empty($form_state['values']['address'])){
    $form['address'] = array(
      '#type' => 'select', 
      '#title' => t('ที่อยู่'), 
      //'#default_value' => variable_get('เลือกจังหวัดที่อาศัย','bkk'),
      '#options' => array_merge(Config::$address_renges, Config::getDbValue('province', 'name')),
    );
  }else{
    $form['address'] = array(
      '#type' => 'select', 
      '#title' => t('ที่อยู่'), 
      '#default_value' => $form_state['values']['address'],
      '#options' => array_merge(Config::$address_renges, Config::getDbValue('province', 'name')),
    );
  }
  if(empty($form_state['values']['hight'])){
    $form['hight'] = array(
      '#type' => 'select', 
      '#title' => t('ส่วนสูง'),
      '#required' =>TRUE, 
      //'#default_value' => variable_get('เลือกส่วนสูง','1'),
      '#options' =>  drupal_map_assoc(array_merge(Config::$hight_renges,range(30,320))),
    );
  }else{
    $form['hight'] = array(
      '#type' => 'select', 
      '#title' => t('ส่วนสูง'),
      '#required' =>TRUE, 
      '#default_value' => $form_state['values']['hight'],
      '#options' =>  drupal_map_assoc(array_merge(Config::$hight_renges,range(30,320))),
    );
  }
  if(empty($form_state['values']['weight'])){
    $form['weight'] = array(
      '#type' => 'select', 
      '#title' => t('น้ำหนัก'),
      '#required' =>TRUE, 
      //'#default_value' => variable_get('เลือกน้ำหนัก','1'),
      '#options' => drupal_map_assoc(array_merge(Config::$weight_renges,range(5,500))), 
    );
  }else{
    $form['weight'] = array(
      '#type' => 'select', 
      '#title' => t('น้ำหนัก'),
      '#required' =>TRUE, 
      '#default_value' =>$form_state['values']['weight'],
      '#options' => drupal_map_assoc(array_merge(Config::$weight_renges,range(5,500))), 
    );
  }
  if(empty($form_state['values']['status'])){
   $form['status'] = array(
      '#type' => 'select', 
      '#title' => t('สถานภาพ'), 
      //'#default_value' => variable_get('เลือกสถานภาพ','1'),
      '#options' => Config::$status_renges,
    
    );
  }else{
    $form['status'] = array(
    '#type' => 'select', 
    '#title' => t('สถานภาพ'), 
    '#default_value' => $form_state['values']['status'],
    '#options' => Config::$status_renges,
    
  );
  }
  $form['page'] = array('#type' => 'hidden', '#value' => 'personal');
    $form['closeDivPop']=$output->closeDiv();
//    $form['closeDivNow']=$output->closeDiv();
  $form['closeGrid']=$output->closeGrid();
  $form['grid1_3']=$output->createGridWithLine(1,'<p></p>');
  
  
  $form['block12'] =$output->createGridWithLine(12);
  
  $form['closeDivPop']=$output->closeDiv();
  $form['closeGrid']=$output->closeGrid();
  $form['closeGrid']=$output->closeGrid();
  //$form['grid1_3']=$output->createGridWithLine(1,'<p></p>');
  $form['block13'] =$output->createGridWithLine(12);
  $form['closeContainer']=$output->closeContainer();
  
  
  $form['white_class'] =$output->openDiv('white_class');
  $form['block5'] = $output->createGrid(4);
  $form['block7'] = $output->openGrid(4);
  
  $form['back'] = array(
    '#type' => 'submit',
    '#value' => t('Back'),
   
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Next'),
   
  );
  $form['c_block7'] =$output->closeGrid();
  $form['block6'] = $output->createGridWithLine(4);
  $form['close_white_class'] =$output->closeDiv();
  
  
  return $form;
}

function check_form($form_state){
  drupal_add_js(drupal_get_path('module', 'howcool') . '/js/fader.js');
  /** get old things
    
  **/
  $form['email']= array('#type' => 'hidden', '#value' => $form_state['values']['email']);
  $form['sex']= array('#type' => 'hidden', '#value' => $form_state['values']['sex']);
  $form['age']= array('#type' => 'hidden', '#value' => $form_state['values']['age']);
  $form['job']= array('#type' => 'hidden', '#value' => $form_state['values']['job']);
  $form['address']= array('#type' => 'hidden', '#value' => $form_state['values']['address']);
  $form['hight']= array('#type' => 'hidden', '#value' => $form_state['values']['hight']);
  $form['weight']= array('#type' => 'hidden', '#value' => $form_state['values']['weight']);
  $form['status']= array('#type' => 'hidden', '#value' => $form_state['values']['status']);
  drupal_set_message(print_r($form['weight'],1));
  /**
     set something
  */
  $output=new DisplayOutput();
  drupal_add_css(drupal_get_path('module', 'howcool') . '/css/check_lists.css');
  
  //old setting
  /*$config = new Config();
  $info = $config->getShows();
  $value = $config->getKeys();*/
  //replace with
  $data =DataManagement::getAllDisplayChecker();
  
  //$info = $data['name'];
  $info = DisplayOutput::renderNamesImages($data);
  $subjects = $subjects['subjects'];
  $value =$data['display_id'];
  
  
  $score = 0;
  
  $form['openContainer'] = $output->openContainer();
  $form['openHeadlineGrid'] = $output->openGrid(12);
  $form['headLine1']= $output->createGridWithLine(12,"<div class='sufon HeadResultTitle HeadResultCenter'>1) ในวันที่ผ่านมาคุณได้ใช้หรือเกี่ยวข้องกับสิ่งเหล่านี้บ้าง (ตอบได้มากกว่า 1 ข้อ)</div> <hr class='white-bottom'/>",'spacer');
    
  /**display check boxes
  */
  $form['closeHeadlineGrid'] = $output->closeLineGrid();
  $form['openGrid'] = $output->openGrid(12);
  $form['opentagDiv'] = $output->openDiv('cool_check');
  if(empty($form_state['values']['count'])){
    $form['point'] = array(
      '#type' => 'checkboxes',
      
      '#options' => array_combine($value,$info),
    );
  }else{    
    $def_value = array();
    for($i=0;$i<$form_state['values']['count'];$i++){
      $def_value[$i]=$form_state['values']['key'.$i];
    }
    $form['point'] = array(
      '#type' => 'checkboxes',
      '#title' => 'วันนี้คุณทำอะไรบ้างคะ',
      '#options' => array_combine($value,$info),
      '#default_value' =>$def_value,
    );
  }
  $form['page'] = array('#type' => 'hidden', '#value' => 'check');  
  $form['closetagDiv'] = $output->closeDiv();
  $form['closeGrid'] = $output->closeLineGrid();
  
  $form['block12'] =$output->createGridWithLine(12); 
  
  $form['closeContainer'] = $output->closeContainer();
  
  $form['white_class'] =$output->openDiv('white_class');
  $form['block5'] = $output->createGrid(4);
  $form['block7'] = $output->openGrid(4);
  
  $form['back'] = array(
    '#type' => 'submit',
    '#value' => t('Back'),
   
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Next'),
   
  );
  $form['c_block7'] =$output->closeGrid();
  $form['block6'] = $output->createGridWithLine(4);
  $form['close_white_class'] =$output->closeDiv();
  
  return $form;
  
}

function scale_form($form_state){
  $output= new DisplayOutput();
  //drupal_add_css(drupal_get_path('module', 'howcool') . '/css/uncompressed/demo.css');
  $config = new Config();
  $form['container']=$output->openContainer();
  $form['headLine1']= $output->createGridWithLine(12,"<div class='sufon HeadResultTitle HeadResultCenter'>2) ตอบคำถามต่อไปนี้โดยประเมินจากวันที่ผ่านมาหรือโดยปกติ</div> <hr class='white-bottom'/>",'spacer');
  /**
    get olds thing
  */
  $form['email']= array('#type' => 'hidden', '#value' => $form_state['values']['email']);
  $form['sex']= array('#type' => 'hidden', '#value' => $form_state['values']['sex']);
  $form['age']= array('#type' => 'hidden', '#value' => $form_state['values']['age']);
  $form['job']= array('#type' => 'hidden', '#value' => $form_state['values']['job']);
  $form['address']= array('#type' => 'hidden', '#value' => $form_state['values']['address']);
  $form['hight']= array('#type' => 'hidden', '#value' => $form_state['values']['hight']);
  $form['weight']= array('#type' => 'hidden', '#value' => $form_state['values']['weight']);
  $form['status']= array('#type' => 'hidden', '#value' => $form_state['values']['status']);
  //$form['point']= array('#type' => 'hidden', '#value' => $form_state['values']['point']); --- got and error
 // drupal_set_message(print_r($form['point'],1));
  
  
  //
  $i=0;
  foreach($form_state['values']['point'] as $key){
    //$myobject = Checker::getChecker($key);
    $data = DataManagement::getScaleData();

    if($key>0){
    //ja run if only if have select ok?
    $scale = array_combine($data[$key]['value'],$data[$key]['label']);
    $form['grid12'.$i] = $output->openGrid(12);  
    $form['subgrid2'.$i] = $output->createGrid(2,"<img src=' " . drupal_get_path('module', 'howcool') ."/".$data[$key]['image_path']."'>",'alpha');      
    $form['subgrid10'.$i] = $output->openGrid(10,'omega'); 
    $form['carbon'.$i] = array('#type' => 'hidden', '#value' => $data[$key]['carbon']);
    $form['water'.$i] = array('#type' => 'hidden', '#value' => $data[$key]['water']);
    $form['key'.$i] = array('#type' => 'hidden', '#value' => $key);
    $form['divpop'.$i] = $output->openDiv('pop');
    $form['divpops'.$i] = $output->openDiv('now');
    $form['scale'.$i] = array(
      '#type' => 'select', 
      '#title' => $data[$key]['subject'], 
      '#options' => $scale, 
      
      );
     $form['closediv'.$i]=$output->closeDiv();
     $form['closedivs'.$i]=$output->closeDiv();
     $form['closesub2'.$i]=$output->closeGrid();
     $form['closegrid12'.$i]=$output->closeLineGrid();
     $i++;
    }
  }
  $form['count']= array('#type' => 'hidden', '#value' => $i);
  $form['page'] = array('#type' => 'hidden', '#value' => 'scale');  

  $form['block12'] =$output->createGridWithLine(12);  
  $form['closeContainer']=$output->closeContainer();
  
  $form['white_class'] =$output->openDiv('white_class');
  $form['block5'] = $output->createGrid(4);
  $form['block7'] = $output->openGrid(4);
  
  $form['back'] = array(
    '#type' => 'submit',
    '#value' => t('Back'),
   
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Next'),
   
  );
  $form['c_block7'] =$output->closeGrid();
  $form['block6'] = $output->createGridWithLine(4);
  $form['close_white_class'] =$output->closeDiv();
  return $form;
}

function logic($form_state){
  $config = new Config();
  $hash = getHash();
  $form['status']= array('#type' => 'hidden', '#value' => $form_state['values']['status']);

  $water = 0;
  $carbon = 0;
  $keep_info=array();
  $keep_info['hash'] =$hash;
  $keep_info['data'] =$data;
  for($i=0;$i<$form_state['values']['count'];$i++){
    $key =$form_state['values']['key'.$i];
    $carbon_value =$form_state['values']['carbon'.$i];
    $water_value =$form_state['values']['water'.$i];
    $scale = $form_state['values']['scale'.$i];
    $water+=$scale*$water_value;
    $carbon+=$scale*$carbon_value;
    $keep_info['data'][$i]['key'] = $key;
    $keep_info['data'][$i]['value'] = $scale;
  }
  $_SESSION['data'] = serialize($keep_info);
  $send_info = array(
    'bid' =>'',
    'hash' =>$hash,
    'selects' => serialize($keep_info),
  
  );  
  drupal_write_record('howcool_behav',$send_info);
  //#sadsad
  $data = array(
    'nid' => '',
    'hash' => $hash,
    'carbon' => $carbon,
    'water' => $water,
    'address' => $form_state['values']['address'],
    'occupation' => $form_state['values']['job'],
    'weight' => $form_state['values']['weight'],
    'height' => $form_state['values']['height'],
    'status' => $form_state['values']['status'],
    'sex' => $form_state['values']['sex'],
    'email' => $form_state['values']['email'],  );
  if(save_result($data)){
    //drupal_set_message('result/'.$hash);
    //drupal_set_message('LOGIC SECTION');
    
    drupal_goto('result/'.$hash);
  }else{
  
  }
}


function form_generation_validate(&$form, &$form_state) {
  //drupal_set_message('ok do');
  drupal_add_css(drupal_get_path('module', 'howcool') . '/css/check_lists.css');
  drupal_add_js(drupal_get_path('module', 'howcool') . '/js/customSelect.jquery.js');
  drupal_add_js(drupal_get_path('module', 'howcool') . '/js/customSelect.js');
  //drupal_set_message($form_state['values']['page'].$form_state['values']['sex']);
  //form_set_error('time', t('An event may not end before it starts.'));
  $values=$form_state['values'];
  $page=$values['page'];
  $errorFlag=0;
  if($page=='personal' && strpos($values['age'],"อายุ")!==false)  {
    ++$errorFlag;
    form_set_error('age', ' ');
    array_pop($_SESSION['messages']['error']);
  }
  else if($page=='check' && array_sum($values['point'])==0) {
     form_set_error('time', t('activity is required!'));
  }
  else if ($page=='email' && strlen(trim($values['email'])) > 0  ) {
    if (!eregi("^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,3})$", $values['email']))
       form_set_error('submitted][email_address', t('Your email address is not valid.'));
      //form_set_error('time',t('email invalid'));  
  }
  
  else { 
    //drupal_set_message('else naja page = '. $page); 
  }

  if ($page=='personal' &&strpos($values['weight'],"น้ำหนัก")!==false)  {
    ++$errorFlag;
    form_set_error('weight', ' ');
    array_pop($_SESSION['messages']['error']);
  }
  if ($page=='personal' && strpos($values['hight'],"สูง")!==false) {
    ++$errorFlag;
    form_set_error('hight', ' ');
    array_pop($_SESSION['messages']['error']);
  }
  if ($page=='personal' && $values['sex']=="null") {
    ++$errorFlag;
    form_set_error('sex', ' ssdfsf');
    array_pop($_SESSION['messages']['error']);
  }    
  if($errorFlag>0) {  form_set_error('sexd', 'กรุณาเลือกข้อมูลที่อยู่ในช่องสีแดง'); }

}

/**
          How Cool Theme Management !!!

*/

function howcool_theme($existing, $type, $theme, $path) {
  return array(
    'headline' => array(
      'arguments' => array('name' => 'npop'),
    ),
  );
}

function theme_headline($name){
  return "<h1>*******$name********</h1><br>";
}

