<?php
//print out form data



function howcool_menu() {
  $items = array();

  $items['form'] = array(
  'title' => 'HowCool!Form',
  'description' => 'Page Decription',
  'page callback' => 'form_view',
  //'page callback' => 'drupal_get_form',
  //'page arguments' => array('popform'),     
  'access arguments' => array('access content'),
  'type' => MENU_NORMAL_ITEM,
  'file' => 'howcool.inc',
  );

  $items['result/%'] = array(
    'title'=> 'HowCool!Result',
    'description'=>'Show result',
    'page callback'=>'result_view',
    'page arguments' => array(1),
    'access arguments'=>array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'howcool.inc',
   
  );
 
  $items['test/insert'] = array(
    'title'=> 'HowCool!InsertTest',
    'description'=>'Show insert',
    'page callback'=>'testInsert',
    'access arguments'=>array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'howcool.inc',
  );
  
  $items['test/view'] = array(
    'title' => 'HowCool!ViewResult',
    'description'=>'Show Result',
    'page callback' => 'testResult',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'howcool.inc'
    );
    
  return $items;
}

/** NAzT

*/

function testInsert() {
  $data = array(
    'nid' => '',
    'hash' => getHash(),
    'carbon' => '12',
    'water' => '13',
    'address' => 'sdfdf',
    'occupation' => 'Student',
    'weight' => '40',
    'height' => '45',
    'status' => 'Single',
    'sex' => 'Male',
    'email' => 'nat.wrw@gmail.com'  );
  if(save_result($data)) 
    return "Inserted";
  else return "error occured (insert)";
}

function testResult() {
  
  return "test result".print_r(get_result('sxws2'),1);
  
}

/**  End NAzT 

*/


/**
    How Cool Display?

*/
function form_view(){
  //$config = new Config();
  //$show = print_r($config->getShows(),1);
  //$show = $config->checkers[0]->display_scale[2];
  $show = 'this is form';
  $show .= drupal_get_form('form_generation',$form_state);
  //$show .= drupal_get_form('email_form',$form_state);
  //$show .= drupal_get_form('personal_form',$form_state);    
  return $show;
}

function result_view($input){
  $show = 'this is result!!'.$input;
  $show .= print_r(get_result($input),1);
  return $show;
}


/**
    How Cool Form Stucture

*/
function form_generation($form_state){
  
  if(empty($form_state['values'])){
    return email_form($form_state);
  }else if($form_state['values']['op']=='Back'){
    return form_back_generation($form_state);
  }else{
    return form_next_generation($form_state);
  
  }
}

function form_next_generation($form_state){
  
  switch($form_state['values']['page']){
    case 'email': return personal_form($form_state);
      break;
    case 'personal': return check_form($form_state);
      break;
     case 'check' : return scale_form($form_state);
      break;
  }
}

function form_back_generation($form_state){
  switch($form_state['values']['page']){
    case 'personal':   return email_form($form_state);
      break; 
    case 'check': return personal_form($form_state);
      break;
     case 'scale' : return check_form($form_state);
      break;
  } 
  
  
}

function form_generation_submit(&$form, &$form_state) {
  $form_state['storage']['values'] = $form_state['values'];
  $form_state['rebuild'] = TRUE;
  //Jumper!!!
  if($form_state['values']['page']=='scale'){
    logic($form_state);
  }
}

function email_form($form_state){
  $form['email'] = array(
    '#type' => 'textfield', 
    '#title' => t('Email'), 
    '#default_value' => t('example@yourmail.com'), 
    '#size' => 60, 
    '#maxlength' => 128, 
    '#required' => TRUE,
  );
  $form['page'] = array('#type' => 'hidden', '#value' => 'email');
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Next'),
   
  );
  return $form;
}

function personal_form($form_state){
  $form['email']= array('#type' => 'hidden', '#value' => $form_state['values']['email']);
  $form['sex'] = array(
    '#type' => 'radios', 
    '#title' => t('เพศ'), 
    //'#default_value' => variable_get('comment_preview', 1), 
    '#options' => array(t('ชาย'), t('หญิง')),
  );
  $form['age'] = array(
    '#type' => 'select', 
    '#title' => t('ช่วงอายุ'), 
  //  '#default_value' => variable_get('เลือกช่วงอายุ','8-13'),
    '#options' => Config::$age_renges,
    //'#description' => t('Global setting for the length of XML feed items that are output by default.'),
  );
  $form['job'] = array(
    '#type' => 'select', 
    '#title' => t('อาชีพ'), 
    //'#default_value' => variable_get('เลือกอาชีพ','student'),
    '#options' => Config::$job_renges,
 
  );
  $form['address'] = array(
    '#type' => 'select', 
    '#title' => t('ที่อยู่'), 
    //'#default_value' => variable_get('เลือกจังหวัดที่อาศัย','bkk'),
    '#options' => Config::$address_renges,
  );
  $form['hight'] = array(
    '#type' => 'select', 
    '#title' => t('ส่วนสูง'), 
    //'#default_value' => variable_get('เลือกส่วนสูง','1'),
    '#options' => Config::$hight_renges,
  );
  $form['weight'] = array(
    '#type' => 'select', 
    '#title' => t('น้ำหนัก'), 
    //'#default_value' => variable_get('เลือกน้ำหนัก','1'),
    '#options' => Config::$weight_renges,
  );
  $form['status'] = array(
    '#type' => 'select', 
    '#title' => t('สถานภาพ'), 
    //'#default_value' => variable_get('เลือกสถานภาพ','1'),
    '#options' => Config::$status_renges,
    
  );
  $form['page'] = array('#type' => 'hidden', '#value' => 'personal');
  $form['back'] = array(
    '#type' => 'submit',
    '#value' => t('Back'),
   
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Next'),
   
  );
  return $form;
}

function check_form($form_state){
  /** get old things
    
  **/
  $form['email']= array('#type' => 'hidden', '#value' => $form_state['values']['email']);
  $form['sex']= array('#type' => 'hidden', '#value' => $form_state['values']['sex']);
  $form['age']= array('#type' => 'hidden', '#value' => $form_state['values']['age']);
  $form['job']= array('#type' => 'hidden', '#value' => $form_state['values']['job']);
  $form['address']= array('#type' => 'hidden', '#value' => $form_state['values']['address']);
  $form['hight']= array('#type' => 'hidden', '#value' => $form_state['values']['hight']);
  $form['weight']= array('#type' => 'hidden', '#value' => $form_state['values']['weight']);
  $form['status']= array('#type' => 'hidden', '#value' => $form_state['values']['status']);

  /**
     set something
  */
  $config = new Config();
  $info = $config->getShows();
  $value = $config->getKeys();
  
  
  $score = 0;
  
  /**display check boxes
  */
  $form['point'] = array(
    '#type' => 'checkboxes',
    '#title' => 'วันนี้คุณทำอะไรบ้างคะ',
    '#options' => array_combine($value,$info),
  );
  
  $form['page'] = array('#type' => 'hidden', '#value' => 'check');  
  $form['back'] = array(
    '#type' => 'submit',
    '#value' => t('Back'),
   
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Next'),
   
  );
  return $form;
  
}

function scale_form($form_state){
  $config = new Config();
  /**
    get olds thing
  */
  $form['email']= array('#type' => 'hidden', '#value' => $form_state['values']['email']);
  $form['sex']= array('#type' => 'hidden', '#value' => $form_state['values']['sex']);
  $form['age']= array('#type' => 'hidden', '#value' => $form_state['values']['age']);
  $form['job']= array('#type' => 'hidden', '#value' => $form_state['values']['job']);
  $form['address']= array('#type' => 'hidden', '#value' => $form_state['values']['address']);
  $form['hight']= array('#type' => 'hidden', '#value' => $form_state['values']['hight']);
  $form['weight']= array('#type' => 'hidden', '#value' => $form_state['values']['weight']);
  $form['status']= array('#type' => 'hidden', '#value' => $form_state['values']['status']);
  

  //
  $i=0;
  foreach($form_state['values']['point'] as $key){
    $myobject = Checker::getChecker($key);
    drupal_set_message($myobject->image);
    if($key>0){
      $scale = array_combine($myobject->scale,$myobject->frequent);
      //drupal_set_message(print_r($key,1));
      $form['key'.$i] =array('#type' => 'hidden', '#value' => $key);
      $form['scale'.$i] =array(
        '#type' => 'select', 
        '#title' => $myobject->frequent_question, 
        //'#default_value' => variable_get('เลือกจังหวัดที่อาศัย','bkk'),
        '#options' => $scale,
      
      );
      $i++;
    }
  }
  $form['count']= array('#type' => 'hidden', '#value' => $i);
  $form['page'] = array('#type' => 'hidden', '#value' => 'scale');  
  $form['back'] = array(
    '#type' => 'submit',
    '#value' => t('Back'),
   
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Next'),
   
  );
  return $form;
  
}

function logic($form_state){
  $config = new Config();
  $hash = getHash();
  $water = 0;
  $carbon = 0;
  for($i=0;$i<$form_state['values']['count'];$i++){
    $key =$form_state['values']['key'.$i];
    $scale = $form_state['values']['scale'.$i];
    $myobject = Checker::getChecker($key);
    $water+=$scale*$myobject->water_factor;
    $carbon+=$scale*$myobject->carbon_factor;
  }
  
  $data = array(
    'nid' => '',
    'hash' => $hash,
    'carbon' => $carbon,
    'water' => $water,
    'address' => $form_state['values']['address'],
    'occupation' => $form_state['values']['job'],
    'weight' => $form_state['values']['weight'],
    'height' => $form_state['values']['height'],
    'status' => $form_state['values']['status'],
    'sex' => $form_state['values']['sex'],
    'email' => $form_state['values']['email'],  );
  if(save_result($data)){
    
    drupal_goto('result/'.$hash);
  }else{
  
  }
  

}

function popform($form_state) {
  $info = array('car','plane','bike');
  $value = array(3,5,0);
  $score=0;
  if(!empty($form_state['values'])){
    
    foreach($form_state['values']['foo'] as $i){
      $score +=$i;
    }
   // $show .= nat(3,20,'carbon');
    drupal_set_message(print_r(nat($score,20,'carbon'),1));
  }
  $form['foo'] = array(
    '#type' => 'checkboxes',
    '#title' => 'วันนี้คุณทำอะไรบ้างคะ',
    '#options' => array_combine($value,$info),
    //'#description' => t('baz'),
  );
  //drupal_set_message(print_r(array_combine($info,$img),1));
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
   
  );
  //$form[ '#action'] =url("admin/result");

  return $form;
}

function popform_submit(&$form, &$form_state) {
  $form_state['storage']['values'] = $form_state['values'];
  $form_state['rebuild'] = TRUE;
  $score = 0;
  foreach($form_state['values']['foo'] as $i){
      $score +=$i;
  }
  drupal_goto('admin/result',array("score"=>$score));
}

/**
          How Cool Theme Management !!!

*/

function howcool_theme($existing, $type, $theme, $path) {
  return array(
    'headline' => array(
      'arguments' => array('name' => 'npop'),
    ),
  );
}

function theme_headline($name){
  return "<h1>*******$name********</h1><br>";
}

