<?php
//print out form data



function howcool_menu() {

  $items = array();

  $items['form'] = array(
  'title' => 'HowCool!Form',
  'description' => 'Page Decription',
  'page callback' => 'form_view',
  //'page callback' => 'drupal_get_form',
  //'page arguments' => array(1),     
  'access arguments' => array('access content'),
  'type' => MENU_NORMAL_ITEM,
  'file' => 'howcool.inc',
  );

  $items['result/%'] = array(
    'title'=> 'HowCool!Result',
    'description'=>'Show result',
    'page callback'=>'result_view',
    'page arguments' => array(1),
    'access arguments'=>array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'howcool.inc',
   
  );
  
  $items['detail/%'] = array(
    'title'=> 'HowCool!Result',
    'description'=>'Show result',
    'page callback'=>'detail_view',
    'page arguments' => array(1),
    'access arguments'=>array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'howcool.inc',
   
  );
  
  $items['management'] =array(
    'title'=> 'HowCool!DataManagement',
    'description'=>'Show Data',
    'page callback'=>'data_view',
    'access arguments'=>array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'datamanagement.inc',
   
  );
  
  return $items;
}


/**
    How Cool Display?

*/

function form_decision($data){

  return $data['page']['#value'];
}


function form_view(){

   drupal_add_css(drupal_get_path('module', 'howcool') . '/css/jquery.ratings.css');
   drupal_add_css(drupal_get_path('module', 'howcool') . '/css/reset.css');
   drupal_add_css(drupal_get_path('module', 'howcool') . '/css/text.css');
   drupal_add_css(drupal_get_path('module', 'howcool') . '/css/960.css');
   drupal_add_js(drupal_get_path('theme', 'foundation') .'/cufon-yui.js', 'theme');
   drupal_add_js(drupal_get_path('theme', 'foundation') .'/supermarket_400.font.js', 'theme');
   //drupal_add_css(drupal_get_path('module', 'howcool') . '/css/uncompressed/demo.css');
  //$show = 'this is form--->';

  $show .= drupal_get_form('form_generation',$form_state);
  return $show;
}

function result_view($input){
  //$show = 'this is result!!'.$input;
  //$show .= print_r(get_result($input),1);
     drupal_add_js(drupal_get_path('theme', 'foundation') .'/cufon-yui.js', 'theme');
     drupal_add_js(drupal_get_path('theme', 'foundation') .'/supermarket_400.font.js', 'theme');
  $show =gen_graph(get_result($input));
  return $show;
}

function detail_view($input){
 drupal_add_css(drupal_get_path('module', 'howcool') . '/css/reset.css');
 drupal_add_css(drupal_get_path('module', 'howcool') . '/css/text.css');
 drupal_add_css(drupal_get_path('module', 'howcool') . '/css/960.css');
 drupal_add_css(drupal_get_path('module', 'howcool') . '/css/check_lists.css');
 $raw_data = DataManagement::getAllDetail();
 $info = array();
  for($i = 0 ;$i<(int)$_SESSION['count'];$i++){
  
    $scale = $_SESSION['value'.$i];

    $info[$i] = array('image_path' => $raw_data[$_SESSION['key'.$i]]['image_path'] ,
                      'name' =>$raw_data[$_SESSION['key'.$i]]['name'],
                      'carbon' =>($raw_data[$_SESSION['key'.$i]]['carbon_factor']*$scale),
                      'water' =>($raw_data[$_SESSION['key'.$i]]['water_factor']*$scale),
                      'scale' =>$scale,
                      );
    
  }
  
  $data = array(
    'carbon' => 3,
    'water' => 5,
    'info'=>$info,
  );
  $r_output = new ResultOutput();
  $output = $r_output->showDetail($data);
  
  return $output;
}

/**
    How Cool Form Stucture

*/
function form_generation($form_state,$page){
  if(empty($form_state['values'])){
    //drupal_set_message(form_decision(email_form($form_state)));  
    return email_form($form_state);
  }else if($form_state['values']['op']=='Back'){
    //drupal_set_message(form_decision(form_back_generation($form_state)));  
    return form_back_generation($form_state);
  }else{
    //drupal_set_message(form_decision(form_next_generation($form_state)));  
    return form_next_generation($form_state);
  
  }
}

function form_next_generation($form_state){
  
  switch($form_state['values']['page']){
    case 'email': return personal_form($form_state);
      break;
    case 'personal': return check_form($form_state);
      break;
     case 'check' : return scale_form($form_state);
      break;
  }
}

function form_back_generation($form_state){
    
  switch($form_state['values']['page'] ){
    case 'personal':   return email_form($form_state);
      break; 
    case 'check': return personal_form($form_state);
      break;
     case 'scale' : return check_form($form_state);
      break;
  } 
  
  
}

function form_generation_submit(&$form, &$form_state) {
  $form_state['storage']['values'] = $form_state['values'];
  $form_state['rebuild'] = TRUE;
  //Jumper!!!
  if($form_state['values']['page']=='scale' && $form_state['values']['op']!='Back'){
    logic($form_state);
  }
}

function email_form($form_state){
  //$form['email']= array('#type' => 'hidden', '#value' => $form_state['values']['email']);
  $form['sex']= array('#type' => 'hidden', '#value' => $form_state['values']['sex']);
  $form['age']= array('#type' => 'hidden', '#value' => $form_state['values']['age']);
  $form['job']= array('#type' => 'hidden', '#value' => $form_state['values']['job']);
  $form['address']= array('#type' => 'hidden', '#value' => $form_state['values']['address']);
  $form['hight']= array('#type' => 'hidden', '#value' => $form_state['values']['hight']);
  $form['weight']= array('#type' => 'hidden', '#value' => $form_state['values']['weight']);
  $form['status']= array('#type' => 'hidden', '#value' => $form_state['values']['status']);
  
  $output = new DisplayOutput();
  $form['openContainer'] = $output->openContainer(12);
  //$form['openGrid']= $output->createGrid(6);
  $form['headLine1']= $output->createGridWithLine(12,"<img src=' ". drupal_get_path('module', 'howcool') . '/images/menupersonal.png' ."'> ",'spacer');
  $form['block1']=$output->createGrid(4);
  $form['openGrid']= $output->openGrid(4);
  //insert picture
  $form['image'] = $output->insertPicture('images/picquiz.png');
  $form['closeGrid'] = $output->closeGrid();
  $form['block2']=$output->createGridWithLine(4);
  $form['block3']=$output->createGrid(4);
  $form['openEmailGrid'] = $output->openGrid(4);
  /*$form['myhtml'] = array(
    '#type'=>'markup',
    '#value'=>theme('headline','Yo Mannn'),
  
  );*/
  if(empty($form_state['values']['email'])){
    $form['email'] = array(
      '#type' => 'textfield', 
      '#title' => t('Email'), 
      '#size' => 30, 
      '#maxlength' => 128, 
      '#required' => TRUE,
    );
  }else{
    $form['email'] = array(
      '#type' => 'textfield', 
      '#title' => t('Email'), 
      '#size' => 30, 
      '#maxlength' => 128, 
      '#default_value' => $form_state['values']['email'],
      '#required' => TRUE,
    );
  }

  $form['page'] = array('#type' => 'hidden', '#value' => 'email');
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Next'),
    
  );
  $form['submit']['#theme'] = 'button';
  $form['submit']['#button_type'] = 'image';
  $form['submit']['#attributes'] = array(
    'src' => drupal_get_path('module', 'howcool') . '/images/menuchoice2.png' ,
    'alt' => t(Search)
  );
  /*
  $form['myhtml_footer'] = array(
    '#type'=>'markup',
    '#value'=>theme('headline','Last Man'),
  
  );
  */
  $form['closeEmailGrid'] = $output->closeGrid();
  $form['block4']=$output->createGrid(4);
  $form['closeContainer'] = $output->closeContainer();
  return $form;
}

function personal_form($form_state){
     drupal_add_js(drupal_get_path('theme', 'foundation') .'/cufon-yui.js', 'theme');
     drupal_add_js(drupal_get_path('theme', 'foundation') .'/supermarket_400.font.js', 'theme');
  $output=new DisplayOutput();
 
  $form['conatiner12']=$output->openContainer();
  $form['headLine1']= $output->createGridWithLine(12,"<img src=' ". drupal_get_path('module', 'howcool') . '/images/menupersonal.png' ."'> ",'spacer');
  $form['grid1_1']=$output->createGrid(1,'<p></p>');
  $form['grid4_111']=$output->createGrid(4,"<img src=' ". drupal_get_path('module', 'howcool') . '/images/p1_0.png' ."'> ");
  $form['grid1_12']=$output->createGrid(1,'<p></p>');
  $form['grid1_13']=$output->openGrid(5,'<p></p>');
  $form['openDiv']=$output->openDiv('pop');
 
  $form['email']= array('#type' => 'hidden', '#value' => $form_state['values']['email']);
  if(empty($form_state['values']['sex'])){
    $form['sex'] = array(
      '#type' => 'select', 
      '#title' => t('เพศ'),
     //'#default_value' => variable_get('comment_preview', 1), 
       '#options' => array("null"=>t('เพศ'),"male"=>t('ชาย'), "female"=>t('หญิง')),
      '#required' =>TRUE,
    );
  }else{
    $form['sex'] = array(
     '#type' => 'select', 
     '#title' => t('เพศ'), 
     '#default_value' => $form_state['values']['sex'],
     '#options' => array("null"=>t('เพศ'),"male"=>t('ชาย'), "female"=>t('หญิง')),
     '#options' => array("male"=>t('ชาย'), "female"=>t('หญิง')),
     '#required' =>TRUE,
    );
  }
 
  if(empty($form_state['values']['age'])){
    $form['age'] = array(
      '#type' => 'select', 
      '#title' => t('ช่วงอายุ'), 
      '#options' => array_merge(Config::$age_renges,drupal_map_assoc(range(1,130))),
      '#required' =>TRUE,
    );
  }else{
    $form['age'] = array(
      '#type' => 'select', 
      '#title' => t('ช่วงอายุ'), 
      '#options' => array_merge(Config::$age_renges,drupal_map_assoc(range(1,130))),
      '#required' =>TRUE,
      '#default_value' => $form_state['values']['age'],
    );
  }
  if(empty($form_state['values']['job'])){
    $form['job'] = array(
      '#type' => 'select', 
      '#title' => t('อาชีพ'), 
      //'#default_value' => variable_get('เลือกอาชีพ','student'),
      '#options' =>array_merge(Config::$job_renges, Config::getDbValue('occupation', 'name')),
 
    );
  }else{
    $form['job'] = array(
      '#type' => 'select', 
      '#title' => t('อาชีพ'), 
      '#default_value' =>  Config::$job_renges,
      '#options' =>array_merge(Config::$job_renges, Config::getDbValue('occupation', 'name')),
 
    );
  }
  if(empty($form_state['values']['address'])){
    $form['address'] = array(
      '#type' => 'select', 
      '#title' => t('ที่อยู่'), 
      //'#default_value' => variable_get('เลือกจังหวัดที่อาศัย','bkk'),
      '#options' => array_merge(Config::$address_renges, Config::getDbValue('province', 'name')),
    );
  }else{
    $form['address'] = array(
      '#type' => 'select', 
      '#title' => t('ที่อยู่'), 
      '#default_value' => $form_state['values']['address'],
      '#options' => array_merge(Config::$address_renges, Config::getDbValue('province', 'name')),
    );
  }
  if(empty($form_state['values']['hight'])){
    $form['hight'] = array(
      '#type' => 'select', 
      '#title' => t('ส่วนสูง'),
      '#required' =>TRUE, 
      //'#default_value' => variable_get('เลือกส่วนสูง','1'),
      '#options' =>  array_merge(Config::$hight_renges,drupal_map_assoc(range(30,320))),
    );
  }else{
    $form['hight'] = array(
      '#type' => 'select', 
      '#title' => t('ส่วนสูง'),
      '#required' =>TRUE, 
      '#default_value' => $form_state['values']['hight'],
      '#options' =>  array_merge(Config::$hight_renges,drupal_map_assoc(range(30,320))),
    );
  }
  if(empty($form_state['values']['weight'])){
    $form['weight'] = array(
      '#type' => 'select', 
      '#title' => t('น้ำหนัก'),
      '#required' =>TRUE, 
      //'#default_value' => variable_get('เลือกน้ำหนัก','1'),
      '#options' =>  array_merge(Config::$weight_renges,drupal_map_assoc(range(5,500))), 
    );
  }else{
    $form['weight'] = array(
      '#type' => 'select', 
      '#title' => t('น้ำหนัก'),
      '#required' =>TRUE, 
      '#default_value' =>$form_state['values']['weight'],
      '#options' => array_merge(Config::$weight_renges,drupal_map_assoc(range(5,500))), 
    );
  }
  if(empty($form_state['values']['status'])){
   $form['status'] = array(
      '#type' => 'select', 
      '#title' => t('สถานภาพ'), 
      //'#default_value' => variable_get('เลือกสถานภาพ','1'),
      '#options' => Config::$status_renges,
    
    );
  }else{
    $form['status'] = array(
    '#type' => 'select', 
    '#title' => t('สถานภาพ'), 
    '#default_value' => $form_state['values']['status'],
    '#options' => Config::$status_renges,
    
  );
  }
  $form['page'] = array('#type' => 'hidden', '#value' => 'personal');
  $form['back'] = array(
    '#type' => 'submit',
    '#value' => t('Back'),
   
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Next'),
   
  );
  
  $form['closeDivPop']=$output->closeDiv();
  $form['closeGrid']=$output->closeGrid();
  $form['grid1_3']=$output->createGridWithLine(1,'<p></p>');
  $form['closeContainer']=$output->closeContainer();
  
  return $form;
}

function check_form($form_state){
  
  /** get old things
    
  **/
  $form['email']= array('#type' => 'hidden', '#value' => $form_state['values']['email']);
  $form['sex']= array('#type' => 'hidden', '#value' => $form_state['values']['sex']);
  $form['age']= array('#type' => 'hidden', '#value' => $form_state['values']['age']);
  $form['job']= array('#type' => 'hidden', '#value' => $form_state['values']['job']);
  $form['address']= array('#type' => 'hidden', '#value' => $form_state['values']['address']);
  $form['hight']= array('#type' => 'hidden', '#value' => $form_state['values']['hight']);
  $form['weight']= array('#type' => 'hidden', '#value' => $form_state['values']['weight']);
  $form['status']= array('#type' => 'hidden', '#value' => $form_state['values']['status']);

  /**
     set something
  */
  $output=new DisplayOutput();
  drupal_add_css(drupal_get_path('module', 'howcool') . '/css/check_lists.css');
  
  //old setting
  /*$config = new Config();
  $info = $config->getShows();
  $value = $config->getKeys();*/
  //replace with
  $data =DataManagement::getAllDisplayChecker();
  
  //$info = $data['name'];
  $info = DisplayOutput::renderNamesImages($data);
  $subjects = $subjects['subjects'];
  $value =$data['display_id'];
  
  $score = 0;
  
  $form['openContainer'] = $output->openContainer();
  $form['openHeadlineGrid'] = $output->openGrid(12);
  $form['headLine1']= $output->createGridWithLine(12,"<img src=' ". drupal_get_path('module', 'howcool') . '/images/menuchoice1.png' ."'> ",'spacer');
    
  /**display check boxes
  */
  $form['closeHeadlineGrid'] = $output->closeLineGrid();
  $form['openGrid'] = $output->openGrid(12);
  $form['opentagDiv'] = $output->openDiv('cool_check');
  if(empty($form_state['values']['count'])){
    $form['point'] = array(
      '#type' => 'checkboxes',
      
      '#options' => array_combine($value,$info),
    );
  }else{    
    $def_value = array();
    for($i=0;$i<$form_state['values']['count'];$i++){
      $def_value[$i]=$form_state['values']['key'.$i];
    }
    $form['point'] = array(
      '#type' => 'checkboxes',
      '#title' => 'วันนี้คุณทำอะไรบ้างคะ',
      '#options' => array_combine($value,$info),
      '#default_value' =>$def_value,
    );
  }
  
  $form['closetagDiv'] = $output->closeDiv();
  $form['closeGrid'] = $output->closeLineGrid();
  $form['arrange_form'] = $output->createGrid(5);
  $form['open_submit'] = $output->openGrid(2);
  $form['opentagForm'] = $output->openDiv('cool_submit');
  $form['page'] = array('#type' => 'hidden', '#value' => 'check');  
  $form['back'] = array(
    '#type' => 'submit',
    '#value' => t('Back'),
   
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Next'),
   
  );
  $form['closetagDivSubmit'] = $output->closeDiv();
  $form['close_submit'] = $output->closeGrid();
  $form['arrange_form2'] = $output->createGridWithLine(5);
  $form['closeContainer'] = $output->closeContainer();
  return $form;
  
}

function scale_form($form_state){
  $output= new DisplayOutput();
  //drupal_add_css(drupal_get_path('module', 'howcool') . '/css/uncompressed/demo.css');
  $config = new Config();
  $form['container']=$output->openContainer();
  $form['headLine1']= $output->createGridWithLine(12,"<img src=' ". drupal_get_path('module', 'howcool') . '/images/menuchoice2.png' ."'> ",'spacer');
  /**
    get olds thing
  */
  $form['email']= array('#type' => 'hidden', '#value' => $form_state['values']['email']);
  $form['sex']= array('#type' => 'hidden', '#value' => $form_state['values']['sex']);
  $form['age']= array('#type' => 'hidden', '#value' => $form_state['values']['age']);
  $form['job']= array('#type' => 'hidden', '#value' => $form_state['values']['job']);
  $form['address']= array('#type' => 'hidden', '#value' => $form_state['values']['address']);
  $form['hight']= array('#type' => 'hidden', '#value' => $form_state['values']['hight']);
  $form['weight']= array('#type' => 'hidden', '#value' => $form_state['values']['weight']);
  $form['status']= array('#type' => 'hidden', '#value' => $form_state['values']['status']);
  //$form['point']= array('#type' => 'hidden', '#value' => $form_state['values']['point']); --- got and error
 // drupal_set_message(print_r($form['point'],1));
  
  
  //
  $i=0;
  foreach($form_state['values']['point'] as $key){
    //$myobject = Checker::getChecker($key);
    $data = DataManagement::getScaleData();
    
    $form['grid12'.$i]=$output->openGrid(12);  
    //$form['subgrid2']=$output->createGrid(2,'sdff'.$img_url,'alpha');   		
    if($key>0){
    //ja run if only if have select ok?
    
    $scale = array_combine($data[$key]['value'],$data[$key]['label']);
    //drupal_set_message(print_r($myobject->image,1));
    // $form['image'.$i]= array('#type'=> 'markup','#value' => $myobject->image);
    $form['grid12'.$i] = $output->openGrid(12);  
    $form['subgrid2'.$i] = $output->createGrid(2,"<img src=' " . drupal_get_path('module', 'howcool') ."/".$data[$key]['image_path']."'>",'alpha');      
    $form['subgrid10'.$i] = $output->openGrid(10,'omega'); 
    $form['carbon'.$i] = array('#type' => 'hidden', '#value' => $data[$key]['carbon']);
    $form['water'.$i] = array('#type' => 'hidden', '#value' => $data[$key]['water']);
    $form['key'.$i] = array('#type' => 'hidden', '#value' => $key);
    $form['divpop'.$i] = $output->openDiv('pop');
    $form['scale'.$i] = array(
      '#type' => 'select', 
      '#title' => $data[$key]['subject'], 
      //'#default_value' => variable_get('เลือกจังหวัดที่อาศัย','bkk'),
      '#options' => $scale, 
      );
     $form['closediv'.$i]=$output->closeDiv();
     $form['closesub2'.$i]=$output->closeGrid();
     $form['closegrid12'.$i]=$output->closeLineGrid();
     $i++;
    }
  }
  
  $form['closeContainer']=$output->closeContainer();
  $form['count']= array('#type' => 'hidden', '#value' => $i);
  $form['page'] = array('#type' => 'hidden', '#value' => 'scale');  
  $form['back'] = array(
    '#type' => 'submit',
    '#value' => t('Back'),
   
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Next'),
   
  );

  return $form;
}

function logic($form_state){
  $config = new Config();
  $hash = getHash();
  $form['status']= array('#type' => 'hidden', '#value' => $form_state['values']['status']);

  $water = 0;
  $carbon = 0;
  
  $_SESSION['count'] = $form_state['values']['count'];
  for($i=0;$i<$form_state['values']['count'];$i++){
    $key =$form_state['values']['key'.$i];
    $carbon_value =$form_state['values']['carbon'.$i];
    $water_value =$form_state['values']['water'.$i];
    $scale = $form_state['values']['scale'.$i];
    $water+=$scale*$water_value;
    $carbon+=$scale*$carbon_value;
    
    $_SESSION['key'.$i]=$key;
    $_SESSION['value'.$i]=$scale;
    
  }
  
  //detail data
  ;
   
 
  //#sadsad
  $data = array(
    'nid' => '',
    'hash' => $hash,
    'carbon' => $carbon,
    'water' => $water,
    'address' => $form_state['values']['address'],
    'occupation' => $form_state['values']['job'],
    'weight' => $form_state['values']['weight'],
    'height' => $form_state['values']['height'],
    'status' => $form_state['values']['status'],
    'sex' => $form_state['values']['sex'],
    'email' => $form_state['values']['email'],  );
  if(save_result($data)){
    //drupal_set_message('result/'.$hash);
    //drupal_set_message('LOGIC SECTION');
    
    drupal_goto('result/'.$hash);
  }else{
  
  }
}


function form_generation_validate(&$form, &$form_state) {
  //drupal_set_message('ok do');
    drupal_add_css(drupal_get_path('module', 'howcool') . '/css/check_lists.css');
  //drupal_set_message($form_state['values']['page'].$form_state['values']['sex']);
  //form_set_error('time', t('An event may not end before it starts.'));
  $values=$form_state['values'];
  $page=$values['page'];
  if($page=='personal' && $values['age']=='null') {
    form_set_error('age', t('age is required!'));
  }
  else if($page=='check' && array_sum($values['point'])==0) {
     form_set_error('time', t('activity is required!'));
  }
  else if ($page=='email' && strlen(trim($values['email'])) > 0  ) {
    if (!eregi("^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,3})$", $values['email']))
       form_set_error('submitted][email_address', t('Your email address is not valid.'));
      //form_set_error('time',t('email invalid'));  
  }
  
  else { 
    //drupal_set_message('else naja page = '. $page); 
  }

  if ($page=='personal' && $values['weight']=="null") {
    form_set_error('weight', t('weight required!'));
  }
  if ($page=='personal' && $values['hight']=="null") {
    form_set_error('hight', t('hight required!'));
  }
  if ($page=='personal' && $values['sex']=="null") {
    form_set_error('sex', t('sex required!'));
  }    
}

/**
          How Cool Theme Management !!!

*/

function howcool_theme($existing, $type, $theme, $path) {
  return array(
    'headline' => array(
      'arguments' => array('name' => 'npop'),
    ),
  );
}

function theme_headline($name){
  return "<h1>*******$name********</h1><br>";
}

